services:
  stumpContainer:
    image: alpine #dummy
    restart: unless-stopped
    logging:
      driver: "${LOG_SERVICE_DRIVER:-json-file}"
      options:
        max-size: "${LOG_SERVICE_SIZE:-50m}"
        max-file: "${LOG_SERVICE_FILES:-3}"
        compress: "true"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
      LANG: "${LANGUAGE:-de_DE.UTF-8}"

  baseContainer:
    extends:
      service: stumpContainer
    volumes:
      - "/etc/ssl/certs:/etc/ssl/certs:ro"

  httpsContainer:
    extends:
      service: baseContainer
    group_add: &runhttps
      - 3000
    tmpfs:
      - /certs
    volumes: &ownCerts
      - type: bind
        source: ${CERT_SERVER_CRT:-/aw/certs/server.crt}
        target: /certs/server.crt
        bind:
          create_host_path: false
      - type: bind
        source: ${CERT_SERVER_KEY:-/aw/certs/server.key}
        target: /certs/server.key
        bind:
          create_host_path: false
      - type: bind
        source: ${CERT_CA_CRT:-/aw/CAs/ca.crt}
        target: /aw/CAs/ca.crt
        bind:
          create_host_path: false
      - type: bind
        source: ./config/https/appsettings.ssl.json
        target: /app/appsettings.Production.json
        bind:
          create_host_path: false
